name: live

on:
  push:
    branches:
      - live

jobs:
  live-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: backup .env
        run: php -r "file_exists('.env') && rename('.env', '.env.development');"
      - name: rename .env.production
        run: php -r "file_exists('.env') || copy('.env.production.live', '.env');"
      - name: Use Node.js 18.8.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.8.0
      - name: Copy .npmrc
        run: php -r "file_exists('.npmrc') || copy('.npmrc.live', '.npmrc');"
      - run: npm install
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - run: npm run build
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          CI: ""
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: website-skeleton.live.ysqhub.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1
          SOURCE_DIR: "dist"
